{- 

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

-}

fibList = map int_fib [0 ..]
	where int_fib 0 = 0
	      int_fib 1 = 1
	      int_fib n = fibList !! (n-2) + fibList !! (n-1)

result = sum $ filter (\x -> x `mod` 2 == 0) $ takeWhile (<4000000) $ fibList